imageRegistry: "****.dkr.ecr.ap-south-1.amazonaws.com"

frontend:
  imageRepo: "mern-frontend"
  tag: "15" "${BUILD_NUMBER}"
  replicaCount: 1

backend:
  imageRepo: "mern-backend"
  tag: "${BUILD_NUMBER}"
  replicaCount: 1
  mongoUri: "mongodb+srv://jayparmar7654321:8XHqZ67aqvdPazmP@cluster0.ffebnid.mongodb.net/?retryWrites=true&w=majority"

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

httpRoute:
  enabled: false
