imageRegistry: "****.dkr.ecr.ap-south-1.amazonaws.com"

frontend:
  imageRepo: "mern-frontend"
  tag: "14" "${BUILD_NUMBER}"
  replicaCount: 1

backend:
  imageRepo: "mern-backend"
  tag: "${BUILD_NUMBER}"
  replicaCount: 1
  