imageRegistry: "****.dkr.ecr.ap-south-1.amazonaws.com"

frontend:
  imageRepo: "mern-frontend"
  tag: "13" "${BUILD_NUMBER}"
  replicaCount: 1

backend:
  imageRepo: "mern-backend"
  tag: "${BUILD_NUMBER}"
  replicaCount: 1

mongodb:
  image: "mongo"
  tag: "${BUILD_NUMBER}"
  storage: "1Gi"