imageRegistry: "633793730349.dkr.ecr.ap-south-1.amazonaws.com"

frontend:
  imageRepo: "mern-frontend"
  tag: "latest"
  replicaCount: 1

backend:
  imageRepo: "mern-backend"
  tag: "16"
  replicaCount: 1

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

httpRoute:
  enabled: false
