apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: mern
  labels:
    app: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      # Use imagePullSecret if your images are private
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: mern-backend
        image: jay2000/mern-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-0.mongo.mern.svc.cluster.local:27017/mern"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 8
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
