apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  namespace: mern
  labels:
    app: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
