apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
  namespace: mern
  labels:
    app: mern-frontend
spec:
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
